// =============================================================================
//
//     Generated by @lite-v3/gqlcodegen (v0.7.1)
//     Schema Timestamp: 2023/11/27 14:28:23 [GMT+7]
//     DO NOT MODIFY BY HAND.
//
//     For more information:
//     - Slack channel: #ask-typescript
//     - Slack group: @wpe-typescript
//
// =============================================================================

// We purposedly disable all linting errors since this file is generated by a
// tool and not directly managed by the developer, hence it might follow a more
// broader rule than the current linter applies.

/* eslint-disable */
// @generated

type Scalars = {
  ID: string;
  String: string;
  Float: number;
  Boolean: boolean;
};

// ================================================================
//
//    [Query] getTweetDetail
//
// ================================================================

// ================================================================
//    [Query] getTweetDetail -- Response
// ================================================================

type getTweetDetail_getTweetDetail_profile = {
  __typename: 'TweetProfile';
  name: Scalars['String'] | null;
  id: Scalars['String'] | null;
  image: Scalars['String'] | null;
  description: Scalars['String'] | null;
};

type getTweetDetail_getTweetDetail = {
  __typename: 'TweetDetailResponse';
  content: Scalars['String'] | null;
  media: Array<Scalars['String']> | null;
  profile: getTweetDetail_getTweetDetail_profile | null;
};

// ================================================================
//    [Query] getTweetDetail -- Entrypoint
// ================================================================

export interface QueryResponsegetTweetDetail {
  getTweetDetail: getTweetDetail_getTweetDetail;
}

export interface QueryInputgetTweetDetail {
  id: Scalars['String'];
}
