// =============================================================================
//
//     Generated by @lite-v3/gqlcodegen (v0.7.1)
//     Schema Timestamp: 2023/11/27 13:18:45 [GMT+7]
//     DO NOT MODIFY BY HAND.
//
//     For more information:
//     - Slack channel: #ask-typescript
//     - Slack group: @wpe-typescript
//
// =============================================================================

// We purposedly disable all linting errors since this file is generated by a
// tool and not directly managed by the developer, hence it might follow a more
// broader rule than the current linter applies.

/* eslint-disable */
// @generated

type Scalars = {
  ID: string;
  String: string;
  Float: number;
  Boolean: boolean;
};

// ================================================================
//
//    [Query] getMentionListenerState
//
// ================================================================

// ================================================================
//    [Query] getMentionListenerState -- Response
// ================================================================

type getMentionListenerState_getMentionListenerState = {
  __typename: 'TwitterListenResponse';
  message: Scalars['String'] | null;
  cronInterval: Scalars['Float'] | null;
  status: Scalars['String'] | null;
  logs: Array<Scalars['String']> | null;
};

// ================================================================
//    [Query] getMentionListenerState -- Entrypoint
// ================================================================

export interface QueryResponsegetMentionListenerState {
  getMentionListenerState: getMentionListenerState_getMentionListenerState;
}

