// =============================================================================
//
//     Generated by @lite-v3/gqlcodegen (v0.7.1)
//     Schema Timestamp: 2023/11/27 13:20:10 [GMT+7]
//     DO NOT MODIFY BY HAND.
//
//     For more information:
//     - Slack channel: #ask-typescript
//     - Slack group: @wpe-typescript
//
// =============================================================================

// We purposedly disable all linting errors since this file is generated by a
// tool and not directly managed by the developer, hence it might follow a more
// broader rule than the current linter applies.

/* eslint-disable */
// @generated

type Scalars = {
  ID: string;
  String: string;
  Float: number;
  Boolean: boolean;
};

// ================================================================
//
//    Input definitions
//
// ================================================================

type ListenTwitterInput = {
  __typename?: 'ListenTwitterInput';
  action?: Scalars['String'] | null;
  cronInterval?: Scalars['Float'] | null;
};


// ================================================================
//
//    [Mutation] listenTwitter
//
// ================================================================

// ================================================================
//    [Mutation] listenTwitter -- Response
// ================================================================

type listenTwitter_terminateAutoReply = {
  __typename: 'TwitterListenResponse';
  message: Scalars['String'] | null;
  status: Scalars['String'] | null;
};

// ================================================================
//    [Mutation] listenTwitter -- Entrypoint
// ================================================================

export interface MutationResponselistenTwitter {
  terminateAutoReply: listenTwitter_terminateAutoReply;
}

export interface MutationInputlistenTwitter {
  data: ListenTwitterInput;
}
